eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kubernetes.docker.internal:8761/eureka/
  instance:
    hostname: kubernetes.docker.internal
